spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:local;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  ldap:
    urls: ldap://localhost:8389
    username: uid=admin,ou=system
    password: password
    base: dc=springframework,dc=org
    embedded:
      ldif: classpath:my-ldap.ldif
      port: 8389
      credential:
        username: uid=admin,ou=system
        password: password
      base-dn: dc=springframework,dc=org
      validation:
        enabled: false



jwt:
  header: Authorization
  secret: mySecret
  expiration: 60000

server:
  port: 8080
  servlet:
    context-path: /spring-server
