spring:
  h2:
    console:
      enabled: @core.h2.enabled@
      path: @core.h2.path@
  datasource:
    url: @core.datasource.url@
    driver-class-name: @core.datasource.driver-class-name@
    username: @core.datasource.username@
    password: @core.datasource.password@
  jpa:
    hibernate:
      ddl-auto: @core.datasource.ddl.auto@
    database-platform: @core.datasource.platform@
    show-sql: true

jwt:
  header: Authorization
  secret: mySecret
  expiration: 60000

server:
  port: 8080
#  servlet:
#    context-path: /spring-server

swagger2:
  enable: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml