INSERT INTO USERS (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (1, 'admin', '$2a$10$vdOFqSqL8857RaG.eW5iEexviO6MpaTAB1M/smIZ6FFhpNCEprUsq', 'admin', 'admin', 'admin@admin.com', 1, '2019-10-14T21:32:29');
INSERT INTO USERS (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (2, 'ethan', '$2a$10$vdOFqSqL8857RaG.eW5iEexviO6MpaTAB1M/smIZ6FFhpNCEprUsq', 'user', 'user', 'enabled@user.com', 1, '2019-10-14T21:32:29');
INSERT INTO USERS (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (3, 'disabled', '$2a$10$vdOFqSqL8857RaG.eW5iEexviO6MpaTAB1M/smIZ6FFhpNCEprUsq', 'user', 'user', 'disabled@user.com', 0, '2019-10-14T21:32:29');

INSERT INTO AUTHORITYS (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITYS (ID, NAME) VALUES (2, 'ROLE_ADMIN');
INSERT INTO AUTHORITYS (ID, NAME) VALUES (3, 'ROLE_OPERATOR');

INSERT INTO USER_AUTHORITYS (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITYS (USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO USER_AUTHORITYS (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO USER_AUTHORITYS (USER_ID, AUTHORITY_ID) VALUES (3, 1);
